version: '3'

services:
  har-fit-app:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: har-fit-docker
    container_name: har-fit-app
    restart: "no"
    ports:
      - "${PORT}:${PORT}"
    environment:
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PORT: ${DB_PORT}
      PORT: ${PORT}
      HOST_API: ${HOST_API}
      JWT_ACCESS_TOKEN_SECRET: ${JWT_ACCESS_TOKEN_SECRET}
      JWT_REFRESH_TOKEN_SECRET: ${JWT_REFRESH_TOKEN_SECRET}
      CLOUDINARY_NAME: ${CLOUDINARY_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
  db:
    image: postgres:16.1
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: harfitdb
    volumes:
      - ./postgres:/var/lib/postgresql/data